name: touriso
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.1
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  go_router: ^8.1.0
  google_fonts: ^5.1.0
  image_picker: ^1.0.1
  intl: ^0.18.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - google_fonts/
